####################################################################################################
# Configuration
# Modify variables below as new releases are made.
# Tag the commit when running the pipeline.
# NOTE: The order in which you write the organsims will determine the order of plots.
####################################################################################################


VERSION = 1509

# source organism information (reference mouse)
srcOrg = C57B6J
srcOrgHgDb = mm10

# this lists all assembly version we wish to keep live in the browser
# the last one is the default
LIVE_VERSIONS = 1411 1504 1509

ifeq (${VERSION},1509)
mappedOrgs = C57B6NJ NZOHlLtJ 129S1 FVBNJ NODShiLtJ LPJ AJ AKRJ BALBcJ DBA2J C3HHeJ CBAJ WSBEiJ CASTEiJ PWKPhJ SPRETEiJ CAROLIEiJ PAHARIEiJ
augustusOrgs = C57B6NJ NZOHlLtJ 129S1 FVBNJ NODShiLtJ LPJ AJ AKRJ BALBcJ DBA2J C3HHeJ CBAJ WSBEiJ CASTEiJ PWKPhJ SPRETEiJ CAROLIEiJ PAHARIEiJ
allOrgs = C57B6J C57B6NJ NZOHlLtJ 129S1 FVBNJ NODShiLtJ LPJ AJ AKRJ BALBcJ DBA2J C3HHeJ CBAJ WSBEiJ CASTEiJ PWKPhJ SPRETEiJ CAROLIEiJ PAHARIEiJ Rattus
GENCODE_VERSION = VM7
TRANS_MAP_VERSION = 2015-10-06
CHAINING_VERSION = 2015-08-19
COMPARATIVE_ANNOTATOR_VERSION = 2015-10-12
haveRnaSeq = yes
rnaSeqStrains = 129S1 AJ AKRJ BALBcJ C3HHeJ C57B6NJ CASTEiJ CBAJ DBA2J LPJ NODShiLtJ NZOHlLtJ PWKPhJ SPRETEiJ WSBEiJ CAROLIEiJ PAHARIEiJ FVBNJ

else ifeq (${VERSION},1504)
mappedOrgs = C57B6NJ NZOHlLtJ 129S1 FVBNJ NODShiLtJ LPJ AJ AKRJ BALBcJ DBA2J C3HHeJ CBAJ WSBEiJ CASTEiJ PWKPhJ SPRETEiJ CAROLIEiJ PAHARIEiJ
augustusOrgs = C57B6NJ NZOHlLtJ 129S1 FVBNJ NODShiLtJ LPJ AJ AKRJ BALBcJ DBA2J C3HHeJ CBAJ WSBEiJ CASTEiJ PWKPhJ SPRETEiJ CAROLIEiJ PAHARIEiJ
allOrgs = C57B6J C57B6NJ NZOHlLtJ 129S1 FVBNJ NODShiLtJ LPJ AJ AKRJ BALBcJ DBA2J C3HHeJ CBAJ WSBEiJ CASTEiJ PWKPhJ SPRETEiJ CAROLIEiJ PAHARIEiJ Rattus
GENCODE_VERSION = VM4
TRANS_MAP_VERSION = 2015-05-28
CHAINING_VERSION = 2015-08-19
COMPARATIVE_ANNOTATOR_VERSION = 2015-09-01
haveRnaSeq = yes
rnaSeqStrains = 129S1 AJ AKRJ BALBcJ C3HHeJ C57B6NJ CASTEiJ CBAJ DBA2J LPJ NODShiLtJ NZOHlLtJ PWKPhJ SPRETEiJ WSBEiJ CAROLIEiJ PAHARIEiJ

else ifeq (${VERSION},1411)
mappedOrgs = C57B6NJ NZOHlLtJ 129S1 FVBNJ NODShiLtJ LPJ AJ AKRJ BALBcJ DBA2J C3HHeJ CBAJ WSBEiJ CASTEiJ PWKPhJ SPRETEiJ 
augustusOrgs = C57B6NJ NZOHlLtJ 129S1 FVBNJ NODShiLtJ LPJ AJ AKRJ BALBcJ DBA2J C3HHeJ CBAJ WSBEiJ CASTEiJ PWKPhJ SPRETEiJ 
allOrgs = C57B6J C57B6NJ NZOHlLtJ 129S1 FVBNJ NODShiLtJ LPJ AJ AKRJ BALBcJ DBA2J C3HHeJ CBAJ WSBEiJ CASTEiJ PWKPhJ SPRETEiJ  Rattus
GENCODE_VERSION = VM4
TRANS_MAP_VERSION = 2015-05-28
COMPARATIVE_ANNOTATOR_VERSION = 2015-09-01
haveRnaSeq = no

else
$(error config.mk variables not defined for VERSION=${VERSION})
endif
